# Generated by Django 5.0.3 on 2024-06-08 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial',
            name='enfermedad',
        ),
        migrations.AddField(
            model_name='em',
            name='enfermedad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='Historia.enfermedad'),
        ),
    ]
