# Generated by Django 5.0.3 on 2024-06-08 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Historia', '0002_remove_historial_enfermedad_em_enfermedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ef',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ef', to='Historia.paciente'),
        ),
        migrations.AddField(
            model_name='em',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='em', to='Historia.paciente'),
        ),
        migrations.AlterField(
            model_name='ef',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='em',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historial',
            name='ef',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historial',
            name='em',
            field=models.CharField(max_length=50),
        ),
    ]
