# Generated by Django 5.0.3 on 2024-06-08 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Historia', '0003_ef_paciente_em_paciente_alter_ef_id_alter_em_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historial',
            old_name='ef',
            new_name='ExamenFisico',
        ),
        migrations.RenameField(
            model_name='historial',
            old_name='em',
            new_name='ExamenMedico',
        ),
    ]
